{{- if and .Values.ingress.enabled .Values.ingress.clusterIssuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "bookstack.fullname" . }}-tls
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ (index .Values.ingress.tls 0).secretName }}
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ (index .Values.ingress.hosts 0).host }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}
