{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bookstack.fullname" . }}-pvc
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join ", " }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
