# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini-config
  namespace: {{ .Release.Namespace }}
data:
  php.ini: |
    post_max_size = 15M
    upload_max_filesize = 15M
    max_execution_time = 90
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    client_max_body_size 100m;
    client_body_timeout 120s;
