replicaCount: 1
#v2.0.1

image:
  repository: lscr.io/linuxserver/bookstack
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
  hosts:
    - host: bookstack.example.com
      paths: ["/"]
  tls:
    - hosts:
        - bookstack.example.com
      secretName: bookstack-tls
  clusterIssuer: letsencrypt-prod

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 10Gi
  storageClass: longhorn

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
  APP_URL: "https://bookstack.example.com"
  DB_HOST: "bookstack-db"
  DB_PORT: "3306"
  DB_USER: "bookstack"
  DB_PASS: "yourdbpass"
  DB_DATABASE: "bookstackapp"
  FILE_UPLOAD_SIZE_LIMIT: 50

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
