#v2.0.0
replicaCount: 1

image:
  repository: lscr.io/linuxserver/bookstack
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: bookstack.example.com
      paths: ["/"]
  tls:
    - hosts:
        - bookstack.example.com
      secretName: bookstack-tls
  clusterIssuer: selfsigned-issuer

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 15Gi
  storageClass: longhorn

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  PUID: 1000
  PGID: 1000
  TZ: Europe/Vienna
  APP_URL: https://bookstack.example.com
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USER: bookstack
  DB_PASS: <your password here>
  DB_DATABASE: bookstack
  FILE_UPLOAD_SIZE_LIMIT: "50"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
