#v1.9.14
replicaCount: 1

image:
  repository: lscr.io/linuxserver/bookstack
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: bookstack.ankhmorpork.dw
      paths: ["/"]
  tls:
    - hosts:
        - bookstack.ankhmorpork.dw
      secretName: bookstack-tls
  clusterIssuer: selfsigned-issuer

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 15Gi
  storageClass: longhorn

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  PUID: 1000
  PGID: 1000
  TZ: Europe/Vienna
  APP_URL: https://bookstack.ankhmorpork.dw
  DB_HOST: mariadb-cluster-mariadb-galera.mariadb-system.svc.cluster.local
  DB_PORT: 3306
  DB_USER: bookstack
  DB_PASS: bsm:Uhap1$adK.B
  DB_DATABASE: bookstack

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
