apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openhab.fullname" . }}
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openhab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openhab.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /openhab/conf
              name: conf
            - mountPath: /openhab/userdata
              name: userdata
            - mountPath: /openhab/addons
              name: addons
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: {{ include "openhab.fullname" . }}-conf
        - name: userdata
          persistentVolumeClaim:
            claimName: {{ include "openhab.fullname" . }}-userdata
        - name: addons
          persistentVolumeClaim:
            claimName: {{ include "openhab.fullname" . }}-addons

