replicaCount: 1

image:
  repository: openhab/openhab
  pullPolicy: IfNotPresent
  tag: "4.1.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "self-signed-issuer"
  hosts:
    - host: openhab.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: openhab-tls
      hosts:
        - openhab.example.com

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 5Gi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
