# openhab/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openhab.fullname" . }}
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openhab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openhab.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "openhab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p {{ .Values.persistence.data.mountPath }} && \
              chown -R {{ .Values.user.id }}:{{ .Values.user.group }} {{ .Values.persistence.data.mountPath }} \ 
              chmod 755 {{ .Values.persistence.data.mountPath }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
              {{- range .Values.persistence.data.subPath }}
            - name: data
              mountPath: {{ .mountPath }}
              subPath: {{ .path }}
              {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "openhab.fullname" . }}
        {{- end }}

