apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openhab.fullname" . }}-conf
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openhab.fullname" . }}-userdata
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openhab.fullname" . }}-addons
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
