# openhab/values.yaml
image:
  repository: openhab/openhab
  tag: 4.1.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443

persistence:
  enabled: true
  accessModes: 
    - ReadWriteOnce
  size: 5Gi
  annotations: {}
  storageClass: "longhorn"

volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
  - name: timezone
    mountPath: /etc/timezone
    readOnly: true
  - name: openhab-addons
    mountPath: /openhab/addons
  - name: openhab-conf
    mountPath: /openhab/conf
  - name: openhab-userdata
    mountPath: /openhab/userdata

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: timezone
    hostPath:
      path: /etc/timezone
  - name: openhab-addons
    persistentVolumeClaim:
      claimName: openhab-addons-pvc
  - name: openhab-conf
    persistentVolumeClaim:
      claimName: openhab-conf-pvc
  - name: openhab-userdata
    persistentVolumeClaim:
      claimName: openhab-userdata-pvc

ingress:
  enabled: true

  className: "nginx"
  annotations:
    kubernetes.io/ingress.className: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  hosts:
    - host: openhab.ankhmorpork.dw
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: openhab
              port:
                number: 8080
  tls:
    - secretName: openhab-tls
      hosts:
        - openhab.ankhmorpork.dw

user:
  id: "9001"
  group: "9001"

extraEnv:
  - name: CRYPTO_POLICY
    value: "unlimited"
  - name: EXTRA_JAVA_OPTS
    value: "-Duser.timezone=Europe/Vienna"
  - name: OPENHAB_HTTP_PORT
    value: "8080"
  - name: OPENHAB_HTTPS_PORT
    value: "8443"
  - name: OH_USER_ID
    value: "9001"
  - name: OH_GROUP_ID
    value: "9001"   

serviceAccount:
  create: true
  name: "openhab"

autoscaling:
  enabled: false

replicaCount: 1
