# openhab/values.yaml
image:
  repository: openhab/openhab
  tag: 4.2.1
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

  # -- Set the correct user id
  USER_ID: 9001
  # -- Set the correct group id
  GROUP_ID: 9001

service:
  main:
    ports:
      http:
        port: 8080
      languageserver:
        enabled: false
        protcol: TCP
        port: 5007
  type: "ClusterIP"

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

persistence:
  conf:
    enabled: false
    storageClass: ""
    accessModes: ReadWriteOnce
    mountPath: /openhab/conf

  userdata:
    enabled: false
    storageClass: ""
    accessModes: ReadWriteOnce
    mountPath: /openhab/userdata

  addons:
    enabled: false
    storageClass: ""
    accessModes: ReadWriteOnce
    mountPath: /openhab/addons

  java:
    enabled: false
    storageClass: ""
    accessModes: ReadWriteOnce
    mountPath: /openhab/.java

serviceAccount:
  create: flase
  name: "openhab"

autoscaling:
  enabled: false

replicaCount: 1
