# openhab/values.yaml
image:
  repository: openhab/openhab
  tag: 4.1.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443

volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
  - name: timezone
    mountPath: /etc/timezone
    readOnly: true

volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: timezone
    hostPath:
      path: /etc/timezone

persistence:
  enabled: true
  addons:
    enabled: false
    mountPath: /openhab/addons
  conf:
    enabled: false
    mountPath: /openhab/conf
  data:
    enabled: true
    mountPath: /openhab
    subPath:
      - mountPath: /openhab/addons
        path: addons
      - mountPath: /openhab/conf
        path: conf
      - mountPath: /openhab/userdata
        path: userdata
  accessModes: ["ReadWriteMany"]
  retain: true
  size: 5Gi
  storageClass: longhorn

ingress:
  enabled: true

  className: "nginx"
  annotations:
    kubernetes.io/ingress.className: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  hosts:
    - host: openhab.ankhmorpork.dw
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: openhab
              port:
                number: 8080
  tls:
    - secretName: openhab-tls
      hosts:
        - openhab.ankhmorpork.dw

user:
  id: "9001"
  group: "9001"
  
extraEnv:
  - name: CRYPTO_POLICY
    value: "unlimited"
  - name: EXTRA_JAVA_OPTS
    value: "-Duser.timezone=Europe/Vienna"
  - name: OPENHAB_HTTP_PORT
    value: "8080"
  - name: OPENHAB_HTTPS_PORT
    value: "8443"
  - name: OH_USER_ID
    value: "9001"
  - name: OH_GROUP_ID
    value: "9001"   

serviceAccount:
  create: true
  name: "openhab"

autoscaling:
  enabled: false

replicaCount: 1
