persistence:
  uploads:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "10Gi"
  storage:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "10Gi"
  phpIniOverride:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "1Mi"
  nginxConfOverride:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "1Mi"
