---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name "uploads" }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
  storageClassName: {{ .Values.persistence.uploads.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name "storage" }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size }}
  storageClassName: {{ .Values.persistence.storage.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name "phpini" }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.phpIniOverride.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.phpIniOverride.size }}
  storageClassName: {{ .Values.persistence.phpIniOverride.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name "nginxconf" }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.nginxConfOverride.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.nginxConfOverride.size }}
  storageClassName: {{ .Values.persistence.nginxConfOverride.storageClass }}
