# values.yaml
# v1.9.7

# General configuration
appKey: ""
appHost: "bookstack.ankhmorpork.dw"  # Replace with your DNS name

# MariaDB configuration (disabled by default)
mariadb:
  enabled: false
  namespace: "mariadb-namespace"
  host: "mariadb-instance"
  port: 3306
  rootUser: "root"
  rootPassword: "yourRootPasswordHere"
  database: "bookstack"
  username: "bookstack"
  password: "yourMariaDBPasswordHere"

# Storage configuration
storageType: "local_secure"

# Persistent volume claims
persistence:
  uploads:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "10Gi"
  storage:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "10Gi"
  phpIniOverride:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "1Mi"
  nginxConfOverride:
    enabled: true
    storageClass: "longhorn"
    accessMode: "ReadWriteOnce"
    size: "1Mi"

# Environment variables
env:
  FILE_UPLOAD_SIZE_LIMIT: "50"
  DB_HOST: ""
  DB_USER: "bookstack"
  DB_PASS: ""
  DB_DATABASE: "bookstack"
  TZ: "UTC"

# SMTP configuration (optional)
smtp:
  enabled: false
  host: ""
  port: 587
  username: ""
  password: ""
  fromAddress: ""
  fromName: ""
