apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deconz.fullname" . }}
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deconz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deconz.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: DECONZ_DEVICE
              value: "{{ .Values.env.DECONZ_DEVICE }}"
            - name: DECONZ_VNC_MODE
              value: "{{ .Values.env.DECONZ_VNC_MODE }}"
            - name: DECONZ_WEB_PORT
              value: "{{ .Values.env.DECONZ_WEB_PORT }}"
            - name: DECONZ_WS_PORT
              value: "{{ .Values.env.DECONZ_WS_PORT }}"
            - name: DECONZ_VNC_PORT
              value: "{{ .Values.env.DECONZ_VNC_PORT }}"
            - name: USBIP_DEVICE
              value: "{{ .Values.env.USBIP_DEVICE }}"
          ports:
            - name: http
              containerPort: {{ .Values.env.DECONZ_WEB_PORT }}
            - name: websocket
              containerPort: {{ .Values.env.DECONZ_WS_PORT }}
            - name: vnc
              containerPort: {{ .Values.env.DECONZ_VNC_PORT }}
