apiVersion: v1
kind: Service
metadata:
  name: {{ include "deconz.fullname" . }}
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.main.ports.http.port }}
      targetPort: {{ .Values.service.main.ports.http.targetPort }}
    - name: websocket
      port: {{ .Values.service.main.ports.websocket.port }}
      targetPort: {{ .Values.service.main.ports.websocket.targetPort }}
    - name: vnc
      port: {{ .Values.service.main.ports.vnc.port }}
      targetPort: {{ .Values.service.main.ports.vnc.targetPort }}
  selector:
    {{- include "deconz.selectorLabels" . | nindent 4 }}
