apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-addons-pvc
  namespace: openhab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
