apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-pvc
  namespace: openhab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
