apiVersion: v1
kind: Service
metadata:
  name: openhab
spec:
  ports:
    - port: {{ .Values.service.main.ports.http.port }}
      targetPort: {{ .Values.service.main.ports.http.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.main.ports.https.port }}
      targetPort: {{ .Values.service.main.ports.https.targetPort }}
      protocol: TCP
      name: https
  selector:
    app: openhab
    